### ISSUE TITLE
Do you still care about repo stars?

### ISSUE THREAD

**Issue by developit** [bevacqua/ama#2]
Just wondering if there's a threshold above which that stuff stops mattering.

**Comment by bevacqua** [comment]
Back when I had few stars I didn't really care about it. It was when some of my repos got 30+ stars that I started becoming obsessed with it. Thankfully I grew past it now, as caring about repo stars is unhealthy.

What I care about these days (and always have) is getting visibility for repos I believe are important. For example, I've always wished [`woofmark`](https://github.com/bevacqua/woofmark) became more popular, just because I think it has a lot of potential and everybody would benefit.
