### ISSUE TITLE
What made you change from C# to JS?

### ISSUE THREAD

**Issue by mii9000** [bevacqua/ama#3]
Why you chose a dynamic language over a statically typed language and built a career on it even though you already had experience in C#?

**Comment by bevacqua** [comment]
Great question. I really really liked C#, particularly because of [how fun my C# learning process was](https://runuo.github.io/runuo/).

A few years ago I read [The Pragmatic Programmer](http://amzn.to/1S6WZdR), a personal favorite. The book suggests getting out of your comfort zone and learning something different every once in a while. I took this idea to heart. At the time, that meant writing some Node.js. In order to keep things interesting I made [a blogging engine](https://github.com/ponyfoo/ponyfoo) I'd actually use. Another part of getting out of the comfort zone was writing articles for a blog. Node.js, in turn, took me to places I had never been before (the command line, UNIX philosophy, Mac/Linux, etc), which was even more valuable for me as a Windows/Microsoft guy (at the time).

I've been writing JavaScript my whole career, though. Before C# it was PHP and JavaScript, and before that it was Front Page, `<blink>` tags, and Java applets.
